#!/usr/bin/env bash

# Check if curl and jq are installed
command -v curl >/dev/null 2>&1 || { echo >&2 "curl is required but not installed. Aborting."; exit 1; }
command -v jq >/dev/null 2>&1 || { echo >&2 "jq is required but not installed. Aborting."; exit 1; }

# Get IP address
ip=$(curl -s https://checkip.amazonaws.com)

# Check for VPN usage
is_vpn=$(curl -s https://ipapi.co/$ip/vpn/)

echo "IP Address: $ip"

# Get location details
location=$(curl -s https://ipapi.co/$ip/json/ | jq -r '.city + ", " + .region + ", " + .country_name')

echo "Location: $location"

# Get ISP and organization details
isp=$(curl -s https://ipapi.co/$ip/json/ | jq -r '.isp + ", " + .org')

echo "ISP and Organization: $isp"

# Check if nslookup is installed
if ! command -v nslookup &> /dev/null
then
    echo "nslookup not found, skipping hostname check"
    nslookup_check=0
else
    nslookup_check=1
fi

# Check hostname if nslookup is installed
if [ $nslookup_check -eq 1 ]; then
    # Get hostname
    hostname=$(nslookup $ip | awk '/name =/{print $4}')
    if [[ ! -z $hostname ]]; then
      echo "Hostname: $hostname"
    fi
fi

# Check for VPN usage
if [[ $is_vpn == "true" ]]; then
  echo "VPN is in use: Yes"
else
  echo "VPN is in use: No"
fi
